version: "2"
services:
  eureka:
    image: "primeton/spring-cloud-eureka-server"
    ports:
      - "8761:8761"
    environment:
      - eureka.instance.hostname=localhost
      - server.port=8761

  configServer:
    image: "primeton/spring-cloud-config-server"
    ports:
      - "8888:8888"
    links:
      - eureka:eureka
      - zipkin:zipkin
    depends_on:
      - eureka
      - zipkin
  #  environment:
  #    - EUREKA_SERVICE_URL=http://huzd.me:8761

  zipkin:
    image: "primeton/spring-cloud-zipkin-server"
    ports:
      - "9411:9411"
    links:
      - eureka:eureka
    depends_on:
      - eureka
  #  environment:
  #    - EUREKA_SERVICE_URL=http://huzd.me:8761

  admin:
    image: "primeton/spring-boot-admin"
    ports:
      - "10086:10086"
    links:
      - eureka:eureka
      - zipkin:zipkin
    depends_on:
      - eureka
      - zipkin
  #  environment:
  #    - EUREKA_SERVICE_URL=http://huzd.me:8761

  hystrixTurbine:
    image: "primeton/hystrix-turbine"
    ports:
      - "9222:9222"
    links:
      - eureka:eureka
      - zipkin:zipkin
    depends_on:
      - eureka
      - zipkin
  #  environment:
  #    - EUREKA_SERVICE_URL=http://huzd.me:8761